Feat/main page
kot91ivan/airbnb-demo-frontend pull request #1
Opened 2018-01-05 05:27 UTC by kot91ivan

Сверстал десктопную версию сайта Airbnb. 
Жень только строгая проверка)

2018-01-05 14:28 UTC, evgenyrodionov commented
Коммиты должны быть на английском — сразу видно, не читал частые ошибки

2018-01-05 14:43 UTC, imevro requested changes
не могу читать этот код — я говорил, что кодстайл превыше всего

и читай частые ошибки, ты прямо их пачками собрал

2018-01-05 14:43 UTC, evgenyrodionov commented on package.json
> +    "flexboxgrid": "^6.3.1",
а зачем это ставить, если есть фбг2?

2018-01-05 14:43 UTC, evgenyrodionov commented on package.json
> +    "flexboxgrid2": "^7.0.0-alpha7",
почему такое старье, если последняя версия 12?

2018-01-05 14:43 UTC, evgenyrodionov commented on src/.eslintrc
> +"parser": "babel-eslint"
почему файл находится в срц
неправильный формат

2018-01-05 14:43 UTC, evgenyrodionov commented on src/App.js
> +const Row = styled.div`
что за роу? я знаю роу из сетки, зачем так же называть?

2018-01-05 14:43 UTC, evgenyrodionov commented on src/App.js
> +  justify-content: center;
зачем это делать? если есть контейнер из сетки

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/bottomFooter.js
> +    display:flex;
откуда 4 пробела? включи преттир

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/bottomFooter.js
> +import IconT from './social/twitter.svg'
не очень классные названия

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/bottomFooter.js
> +const Item = styled.div`
читай частые ошибки

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/bottomFooter.js
> +        <Item className='col-xs-8 col-sm-6 col-md-4'>
бля, преттир включи

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/bottomFooter.js
> +        <div className='col-xs-0 col-sm-3 col-md-6'></div>
что за col-xs-0?

2018-01-05 14:43 UTC, evgenyrodionov commented on src/Footer/index.js
> +import MainFooter from './mainFooter';
ты и так в футере, зачем эти постфиксы?

2018-01-05 21:13 UTC, kot91ivan commented
Fixes all comments. 
Additionally fixed main divs in components. 
I re-read "frequent errors") And learned to use prettier.

I want more code.

2018-01-06 11:03 UTC, imevro requested changes
очень хуёво: семантика нулевая, стиль именования постоянно скачет, преттир не настроен

ты уроки открывал вообще?

2018-01-06 11:03 UTC, evgenyrodionov commented on .vscode/settings.json
> +{
а зачем эта директория тут? выкинь и в гитигнор — проекту плевать на твои настройки редактора

2018-01-06 11:03 UTC, evgenyrodionov commented on src/App.js
> +  @media (min-device-width: 991px) {
min-width мб?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/App.js
> +    padding: 0 79px;
что это? там же сетка

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +import GreyLogo from './gray-logo.svg';
grey from gray

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +import Twitter from './social/twitter.svg';
а зачем это разделение на social?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +const Copyright = styled.span`
ставь переносы между объявлениями — неудобно читать же

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +const Nav = styled.div`
нав = див? где проебал семантику?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +    <div className="col-sm-3 col-md-6" />
оффсеты есть

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/Path-1.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
это что за файл вообще? Path-1.svg?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +  -moz-appearance: none;
в ск есть автопрефиксер

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Footer/index.js
> +  @media (max-device-width: 768px) {
читай урок про мобайл фёст в курсе про вёрстку

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Header/index.js
> +      <div className="col-sm-1 col-md-1">
зачем тут сетка?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Header/index.js
> +const Header = styled.div`
мб header?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Header/index.js
> +import logo from './icon/logo.svg';
зачем директория икон?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Header/index.js
> +import Nav from './nav';
если это компонент, то почему нав с маленькой буквы?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Header/nav.js
> +const Nav = styled.div`
http://htmlreference.io/element/nav/

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/Explore.js
> +        <Card>
и как перейти по ссылке?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/Featured.js
> +import {Title, Section, Arrow, LinkAll} from './Styled';
пиздец, куда ты преттир проебал? ты его вообще настраивал в редакторе?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/Featured.js
> +import React from 'react';
почему файл лежит в Featured.js, если всё, что к нему относится, находится в директории featured? Положи в Featured/index.js и читай внимательнее второй урок

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/Featured.js
> +const FirstTitle = styled.div`
тайтл = див? где семантика? ты знаешь только див?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/Featured.js
> +      <div className="col-xs-6 col-sm-6 col-md-6">
зачем в заголовках сетка?

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/home.js
> +          <Star />161 · Superhost
Star это одна звезда

2018-01-06 11:03 UTC, evgenyrodionov commented on src/Main/index.js
> +const Main = styled.div`
http://htmlreference.io/element/main/

2018-01-06 11:28 UTC, kot91ivan commented on src/App.js
> +    padding: 0 79px;
Сетка хуетка честно говоря, она на всю страницу растягивается в макете там отступы примерно 79px

2018-01-06 20:47 UTC, kot91ivan commented
Все ошибки исправил, касательно Сетки у заголовков там они вылазят за сетку и тогда уже не красиво.

2018-01-07 21:31 UTC, imevro requested changes

2018-01-07 21:31 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +    <div className="col-sm-offset-1 col-md-offset-5" />
зачем так? вешай на следующий блок

2018-01-07 21:31 UTC, evgenyrodionov commented on src/Footer/index.js
> +import InputArrow from './icondown.svg';
если это иконка, то `camelCase`, а не `PascalCase`

2018-01-08 06:02 UTC, merged